function output = run_S3_suffix_average_sensitivity(max_iter_local)
%RUN_S3_SUFFIX_AVERAGE_SENSITIVITY Compare A1/A2/A3 on community 1 only.
% This script does not call upperMarketS3 and does not touch S0-S2.

if nargin < 1 || isempty(max_iter_local)
    max_iter_local = 10000;
end

load('params.mat');
community_id = 1;
idx = start_idx(community_id):end_idx(community_id);
timestamp = datestr(now,'yyyymmdd_HHMMSS');

policy_names = {'A1_early','A2_recommended','A3_strict'};
cv_factors = [10,5,2];
price_factors = [20,10,5];
stable_windows = [20,20,20];
mode_names = {'deterministic','fast_qre'};
output_files = cell(numel(policy_names),numel(mode_names));
summary_rows = cell(0,1);

for policy_idx = 1:numel(policy_names)
    avg_config = struct('policy','dynamic_stable_start', ...
        'start_cv_factor',cv_factors(policy_idx), ...
        'start_price_factor',price_factors(policy_idx), ...
        'start_stable_window',stable_windows(policy_idx), ...
        'min_price_updates',inner_avg_min_price_updates, ...
        'min_samples',inner_avg_min_samples);

    for mode_idx = 1:numel(mode_names)
        qre_noise_enabled_local = mode_idx == 2;
        rng_config = struct('inner_delay_seed',rng_seeds.inner_delay, ...
            'qre_noise_seed',rng_seeds.qre_noise, ...
            'qre_audit_seed',rng_seeds.qre_audit);

        diagnostic = localMarket_S3( ...
            c(idx),b(idx),a(community_id),D(idx),init_rho(community_id), ...
            pg_max(idx),pg_min(idx),init_pi(community_id),init_pes(idx), ...
            init_pg(idx),init_pb(idx),init_ps(idx),init_pesc(community_id), ...
            errTol_LESMs(community_id),inner_cv_tol_kW(community_id), ...
            init_pi_0(community_id),pi_max,pi_min,true,beta_qre(idx), ...
            qre_epsilon,agg_epsilon_i(community_id),qre_z_cap, ...
            qre_backoff_factor,qre_max_backoffs,inner_momentum, ...
            max_iter_local,h0_max,min_inner_iter,inner_avg_start_iter, ...
            inner_cv_stop_enabled,qre_certificate_enabled, ...
            agg_certificate_enabled,agg_cert_tol,stable_inner_window, ...
            qre_audit_enabled,qre_audit_rate,qre_audit_trace_community_full, ...
            qre_audit_seed,agg_gap_diagnostic_enabled,qre_noise_enabled_local, ...
            diagnostic_record_every,exact_sync_diagnostic_every,rolling_window, ...
            false,inf,1,community_id,rng_config,avg_config);

        diagnostic_config = avg_config;
        diagnostic_config.mode = mode_names{mode_idx};
        diagnostic_config.policy_name = policy_names{policy_idx};
        diagnostic_config.community_id = community_id;
        diagnostic_config.max_inner_iter = max_iter_local;
        diagnostic_config.qre_noise_enabled = qre_noise_enabled_local;
        diagnostic_config.params_run_profile = run_profile;
        diagnostic_config.timestamp = timestamp;

        filename = sprintf('S3_suffix_average_%s_%s_community_%d_max_%d_%s.mat', ...
            policy_names{policy_idx},mode_names{mode_idx},community_id, ...
            max_iter_local,timestamp);
        save(filename,'diagnostic','diagnostic_config','-v7');
        output_files{policy_idx,mode_idx} = fullfile(pwd,filename);

        summary_rows{end+1,1} = struct( ...
            'policy',policy_names{policy_idx}, ...
            'mode',mode_names{mode_idx}, ...
            'averaging_started',diagnostic.averaging_started, ...
            'start_wall_iter',diagnostic.inner_avg_start_wall_iter, ...
            'start_price_update',diagnostic.inner_avg_start_price_update, ...
            'start_held_cv',getTraceAtStart(diagnostic,'trace_cv_held_kW'), ...
            'start_lambda_step',getTraceAtStart(diagnostic,'trace_lambda_step'), ...
            'stop_wall_iter',diagnostic.wall_iter, ...
            'avg_cnt',diagnostic.inner_avg_cnt, ...
            'formal_cv',diagnostic.final_formal_cv_kW, ...
            'held_cv',diagnostic.final_held_cv_kW, ...
            'rolling_cv',diagnostic.cv_rolling_final_kW, ...
            'lambda_error',diagnostic.final_lambda_error, ...
            'qre_gap_max',diagnostic.qre_gap_max, ...
            'qre_gap_mean',diagnostic.qre_gap_mean, ...
            'qre_gap_p95',diagnostic.qre_gap_p95, ...
            'qre_gap_exceed_count',diagnostic.qre_gap_exceed_count, ...
            'delay_hash',diagnostic.delay_sequence_hash, ...
            'update_hash',diagnostic.update_sequence_hash, ...
            'runtime_seconds',NaN);
    end

    deterministic = load(output_files{policy_idx,1},'diagnostic');
    fast_qre = load(output_files{policy_idx,2},'diagnostic');
    same_delay = strcmp(deterministic.diagnostic.delay_sequence_hash, ...
        fast_qre.diagnostic.delay_sequence_hash);
    same_updates = strcmp(deterministic.diagnostic.update_sequence_hash, ...
        fast_qre.diagnostic.update_sequence_hash);
    fprintf('[%s] same_delay=%d same_updates=%d start=%g/%g stop=%g/%g final_formal_cv=%.6g/%.6g\n', ...
        policy_names{policy_idx},same_delay,same_updates, ...
        deterministic.diagnostic.inner_avg_start_wall_iter, ...
        fast_qre.diagnostic.inner_avg_start_wall_iter, ...
        deterministic.diagnostic.wall_iter,fast_qre.diagnostic.wall_iter, ...
        deterministic.diagnostic.final_formal_cv_kW, ...
        fast_qre.diagnostic.final_formal_cv_kW);
end

output = struct('files',{output_files},'summary',{summary_rows}, ...
    'community_id',community_id,'max_inner_iter',max_iter_local, ...
    'timestamp',timestamp);
save(sprintf('S3_suffix_average_sensitivity_summary_community_%d_%s.mat', ...
    community_id,timestamp),'output','-v7');
print_summary(summary_rows);
end

function value = getTraceAtStart(diagnostic,field_name)
if isnan(diagnostic.inner_avg_start_wall_iter)
    value = NaN;
    return;
end
idx = find(diagnostic.trace_h == diagnostic.inner_avg_start_wall_iter,1,'last');
if isempty(idx)
    idx = find(diagnostic.trace_h <= diagnostic.inner_avg_start_wall_iter,1,'last');
end
if isempty(idx)
    value = NaN;
else
    value = diagnostic.(field_name)(idx);
end
end

function print_summary(summary_rows)
fprintf('\npolicy mode started start_h start_update stop_h avg_cnt formal_cv held_cv rolling_cv lambda_err qre_gap_max delay_hash update_hash\n');
for i = 1:numel(summary_rows)
    s = summary_rows{i};
    fprintf('%s %s %d %g %g %g %g %.6g %.6g %.6g %.6g %.6g %s %s\n', ...
        s.policy,s.mode,s.averaging_started,s.start_wall_iter, ...
        s.start_price_update,s.stop_wall_iter,s.avg_cnt,s.formal_cv, ...
        s.held_cv,s.rolling_cv,s.lambda_error,s.qre_gap_max, ...
        s.delay_hash,s.update_hash);
end
end
