function report = run_S2_sync_barrier_single_community_test()
%RUN_S2_SYNC_BARRIER_SINGLE_COMMUNITY_TEST Audit S2 local sync counting only.

root = fileparts(mfilename('fullpath'));
cd(root);
p = load('params.mat');
community_id = 1;
s = p.start_idx(community_id):p.end_idx(community_id);
rng_config = struct('inner_delay_seed',p.rng_seeds.inner_delay, ...
    'qre_noise_seed',p.rng_seeds.qre_noise,'qre_noise_enabled',false);
avg_config = struct('policy','A2_dynamic_stable_start', ...
    'policy_version','A2_dynamic_stable_start_v1', ...
    'start_cv_factor',p.inner_avg_start_cv_factor, ...
    'start_price_factor',p.inner_avg_start_price_factor, ...
    'start_stable_window',p.inner_avg_start_stable_window, ...
    'min_price_updates',p.inner_avg_min_price_updates, ...
    'min_samples',p.inner_avg_min_samples, ...
    'formal_cv_stable_window',p.inner_formal_cv_stable_window, ...
    'price_stable_window',p.stable_inner_window);

max_test_price_updates = 450;
t0 = tic;
r = localMarket_S2(p.c(s),p.b(s),p.a(community_id),p.D(s), ...
    p.init_rho(community_id),p.pg_max(s),p.pg_min(s),p.init_pi(community_id), ...
    p.init_pes(s),p.init_pg(s),p.init_pb(s),p.init_ps(s), ...
    p.init_pesc(community_id),p.errTol_LESMs(community_id), ...
    p.inner_cv_tol_kW(community_id),p.init_pi_0(community_id),p.pi_max,p.pi_min, ...
    true,p.beta_qre(s),p.qre_epsilon,p.agg_epsilon_i(community_id), ...
    p.qre_z_cap,p.qre_backoff_factor,p.inner_momentum,max_test_price_updates, ...
    p.h0_max,1,p.inner_avg_start_iter,p.inner_cv_stop_enabled, ...
    false,false,false,inf,1,community_id,rng_config,avg_config,1);
runtime_s = toc(t0);

% 额外的短程计数探针仅用于验证“启动后每个同步周期最多一个样本”。
% 它放宽启动门槛，不用于宣称 A2 数值性能。
probe_config = avg_config;
probe_config.start_cv_factor = 1e12;
probe_config.start_price_factor = 1e12;
probe_config.start_stable_window = 2;
probe_config.min_price_updates = 2;
probe_config.min_samples = 3;
probe_config.formal_cv_stable_window = 2;
probe_config.price_stable_window = 2;
probe = localMarket_S2(p.c(s),p.b(s),p.a(community_id),p.D(s), ...
    p.init_rho(community_id),p.pg_max(s),p.pg_min(s),p.init_pi(community_id), ...
    p.init_pes(s),p.init_pg(s),p.init_pb(s),p.init_ps(s), ...
    p.init_pesc(community_id),p.errTol_LESMs(community_id), ...
    p.inner_cv_tol_kW(community_id),p.init_pi_0(community_id),p.pi_max,p.pi_min, ...
    true,p.beta_qre(s),p.qre_epsilon,p.agg_epsilon_i(community_id), ...
    p.qre_z_cap,p.qre_backoff_factor,p.inner_momentum,20, ...
    p.h0_max,1,p.inner_avg_start_iter,p.inner_cv_stop_enabled, ...
    false,false,false,inf,1,community_id,rng_config,probe_config,1);
probe_event = logical(probe.trace_update_event(:));
probe_price_delta = diff(probe.trace_price_update_count(:));
probe_avg_delta = diff(probe.trace_avg_cnt(:));
probe_average_count_pass = probe.averaging_started && probe.inner_avg_cnt > 0 && ...
    probe.inner_avg_cnt == max(probe.trace_avg_cnt) && ...
    all(probe_avg_delta <= double(probe_event(2:end))) && ...
    all(probe_avg_delta(~probe_event(2:end)) == 0);
probe_barrier_count_pass = all(probe_price_delta == double(probe_event(2:end)));
probe_metrics = table(probe.wall_iter,probe.price_update_count, ...
    probe.inner_avg_cnt,probe.inner_avg_start_price_update, ...
    probe.formal_cv_kW,{probe.stop_reason},probe_average_count_pass, ...
    probe_barrier_count_pass,'VariableNames',{'wall_iter','price_update_count', ...
    'avg_cnt','avg_start_price_update','formal_cv_kW','stop_reason', ...
    'average_count_pass','barrier_count_pass'});

event = logical(r.trace_update_event(:));
price_count = r.trace_price_update_count(:);
avg_count = r.trace_avg_cnt(:);
delta_price = diff(price_count);
delta_avg = diff(avg_count);
expected_delta_price = double(event(2:end));
barrier_price_count_pass = all(delta_price == expected_delta_price);
waiting_price_hold_pass = all(delta_price(~event(2:end)) == 0);
waiting_average_hold_pass = all(delta_avg(~event(2:end)) == 0);
average_only_on_update_pass = all(delta_avg <= double(event(2:end)));
average_count_pass = r.inner_avg_cnt == max(avg_count) && ...
    r.inner_avg_cnt <= r.price_update_count;
cycle_response_count_pass = r.eu_response_count == ...
    r.price_update_count * numel(s);
wall_ge_cycle_pass = r.wall_iter >= r.price_update_count;
formal_window_pass = ~r.averaging_started || ...
    r.inner_avg_cnt < avg_config.min_samples || ...
    islogical(r.formal_cv_stable_pass) || isnumeric(r.formal_cv_stable_pass);

pass = barrier_price_count_pass && waiting_price_hold_pass && ...
    waiting_average_hold_pass && average_only_on_update_pass && ...
    average_count_pass && cycle_response_count_pass && wall_ge_cycle_pass && ...
    formal_window_pass && probe_average_count_pass && probe_barrier_count_pass;
metrics = table(community_id,r.wall_iter,r.price_update_count, ...
    r.eu_response_count,r.inner_avg_cnt,r.inner_avg_start_price_update, ...
    r.formal_cv_kW,r.formal_cv_stable_pass,{r.stop_reason},runtime_s, ...
    barrier_price_count_pass,waiting_price_hold_pass,waiting_average_hold_pass, ...
    average_only_on_update_pass,average_count_pass,cycle_response_count_pass, ...
    wall_ge_cycle_pass,pass,'VariableNames',{'community_id','wall_iter', ...
    'price_update_count','eu_response_count','avg_cnt','avg_start_price_update', ...
    'formal_cv_kW','formal_cv_stable_pass','stop_reason','runtime_s', ...
    'barrier_price_count_pass','waiting_price_hold_pass', ...
    'waiting_average_hold_pass','average_only_on_update_pass', ...
    'average_count_pass','cycle_response_count_pass','wall_ge_cycle_pass','pass'});
report = struct('metrics',metrics,'pass',pass, ...
    'probe_metrics',probe_metrics,'probe_pass',probe_average_count_pass && probe_barrier_count_pass, ...
    'sync_cycle_count',r.price_update_count,'wall_clock_count',r.wall_iter, ...
    'eu_response_count',r.eu_response_count,'avg_sample_count',r.inner_avg_cnt, ...
    'formal_cv_kW',r.formal_cv_kW,'stop_reason',r.stop_reason, ...
    'seed_derivation_policy',r.seed_derivation_policy, ...
    'qre_noise_enabled',rng_config.qre_noise_enabled);
save('S2_sync_barrier_single_community_test.mat','report','metrics');
writetable(metrics,'S2_sync_barrier_single_community_test.csv');
writetable(probe_metrics,'S2_sync_barrier_counting_probe.csv');
disp(metrics);
fprintf('S2 sync-barrier single-community audit: %s\n',ternary(pass,'PASS','FAIL'));

    function value = ternary(condition,true_value,false_value)
        if condition, value = true_value; else, value = false_value; end
    end
end
