function output = run_S3_suffix_average_representative(max_iter_local,community_ids_local)
%RUN_S3_SUFFIX_AVERAGE_REPRESENTATIVE Validate frozen A2 on five communities.
% This script runs localMarket_S3 only; it does not call upperMarketS3.

if nargin < 1 || isempty(max_iter_local)
    max_iter_local = 10000;
end
if nargin < 2 || isempty(community_ids_local)
    community_ids_local = [3,1,49,71,123];
end

load('params.mat');
community_ids = community_ids_local;
timestamp = datestr(now,'yyyymmdd_HHMMSS');
avg_config = struct('policy','dynamic_stable_start', ...
    'start_cv_factor',inner_avg_start_cv_factor, ...
    'start_price_factor',inner_avg_start_price_factor, ...
    'start_stable_window',inner_avg_start_stable_window, ...
    'min_price_updates',inner_avg_min_price_updates, ...
    'min_samples',inner_avg_min_samples);
mode_names = {'deterministic','fast_qre'};
output_files = cell(numel(community_ids),numel(mode_names));
summary_rows = cell(0,1);

for community_pos = 1:numel(community_ids)
    community_id = community_ids(community_pos);
    idx = start_idx(community_id):end_idx(community_id);
    community_load = sum(D(idx));
    for mode_idx = 1:numel(mode_names)
        qre_noise_enabled_local = mode_idx == 2;
        rng_config = struct('inner_delay_seed',rng_seeds.inner_delay, ...
            'qre_noise_seed',rng_seeds.qre_noise, ...
            'qre_audit_seed',rng_seeds.qre_audit);
        diagnostic = localMarket_S3( ...
            c(idx),b(idx),a(community_id),D(idx),init_rho(community_id), ...
            pg_max(idx),pg_min(idx),init_pi(community_id),init_pes(idx), ...
            init_pg(idx),init_pb(idx),init_ps(idx),init_pesc(community_id), ...
            errTol_LESMs(community_id),inner_cv_tol_kW(community_id), ...
            init_pi_0(community_id),pi_max,pi_min,true,beta_qre(idx), ...
            qre_epsilon,agg_epsilon_i(community_id),qre_z_cap, ...
            qre_backoff_factor,qre_max_backoffs,inner_momentum, ...
            max_iter_local,h0_max,min_inner_iter,inner_avg_start_iter, ...
            inner_cv_stop_enabled,qre_certificate_enabled, ...
            agg_certificate_enabled,agg_cert_tol,stable_inner_window, ...
            qre_audit_enabled,qre_audit_rate,qre_audit_trace_community_full, ...
            qre_audit_seed,agg_gap_diagnostic_enabled,qre_noise_enabled_local, ...
            diagnostic_record_every,exact_sync_diagnostic_every,rolling_window, ...
            false,inf,1,community_id,rng_config,avg_config);

        diagnostic_config = avg_config;
        diagnostic_config.community_id = community_id;
        diagnostic_config.community_size = numel(idx);
        diagnostic_config.community_load_kW = community_load;
        diagnostic_config.mode = mode_names{mode_idx};
        diagnostic_config.max_inner_iter = max_iter_local;
        diagnostic_config.qre_noise_enabled = qre_noise_enabled_local;
        diagnostic_config.timestamp = timestamp;
        filename = sprintf('S3_suffix_A2_%s_community_%d_max_%d_%s.mat', ...
            mode_names{mode_idx},community_id,max_iter_local,timestamp);
        save(filename,'diagnostic','diagnostic_config','-v7');
        output_files{community_pos,mode_idx} = fullfile(pwd,filename);

        summary_rows{end+1,1} = struct( ...
            'community_id',community_id,'community_size',numel(idx), ...
            'community_load_kW',community_load,'mode',mode_names{mode_idx}, ...
            'averaging_started',diagnostic.averaging_started, ...
            'start_wall_iter',diagnostic.inner_avg_start_wall_iter, ...
            'start_price_update',diagnostic.inner_avg_start_price_update, ...
            'stop_wall_iter',diagnostic.wall_iter, ...
            'avg_cnt',diagnostic.inner_avg_cnt, ...
            'formal_cv_kW',diagnostic.final_formal_cv_kW, ...
            'held_cv_kW',diagnostic.final_held_cv_kW, ...
            'rolling_cv_kW',diagnostic.cv_rolling_final_kW, ...
            'lambda_error',diagnostic.final_lambda_error, ...
            'qre_gap_max',diagnostic.qre_gap_max, ...
            'qre_gap_mean',diagnostic.qre_gap_mean, ...
            'qre_gap_p95',diagnostic.qre_gap_p95, ...
            'qre_gap_exceed_count',diagnostic.qre_gap_exceed_count, ...
            'delay_hash',diagnostic.delay_sequence_hash, ...
            'update_hash',diagnostic.update_sequence_hash);
    end

    det = load(output_files{community_pos,1},'diagnostic');
    qre = load(output_files{community_pos,2},'diagnostic');
    fprintf('community=%d n=%d load=%.3f same_delay=%d same_updates=%d start=%g/%g stop=%g/%g formal_cv=%.6g/%.6g\n', ...
        community_id,numel(idx),community_load, ...
        strcmp(det.diagnostic.delay_sequence_hash,qre.diagnostic.delay_sequence_hash), ...
        strcmp(det.diagnostic.update_sequence_hash,qre.diagnostic.update_sequence_hash), ...
        det.diagnostic.inner_avg_start_wall_iter,qre.diagnostic.inner_avg_start_wall_iter, ...
        det.diagnostic.wall_iter,qre.diagnostic.wall_iter, ...
        det.diagnostic.final_formal_cv_kW,qre.diagnostic.final_formal_cv_kW);
end

output = struct('files',{output_files},'summary',{summary_rows}, ...
    'community_ids',community_ids,'max_inner_iter',max_iter_local, ...
    'timestamp',timestamp);
save(sprintf('S3_suffix_A2_representative_summary_%s.mat',timestamp), ...
    'output','-v7');
end
