function report = run_S3_repeated_local_call_rng_test()
%RUN_S3_REPEATED_LOCAL_CALL_RNG_TEST Audit keyed random streams over local calls.

root = fileparts(mfilename('fullpath'));
cd(root);
params = load('params.mat');
community_id = 1;
call_counts = [1 2 3];
max_test_iter = 800;

rng_config = struct('inner_delay_seed',params.rng_seeds.inner_delay, ...
    'qre_noise_seed',params.rng_seeds.qre_noise, ...
    'qre_audit_seed',params.rng_seeds.qre_audit);
avg_config = struct('policy',params.inner_avg_policy, ...
    'start_cv_factor',params.inner_avg_start_cv_factor, ...
    'start_price_factor',params.inner_avg_start_price_factor, ...
    'start_stable_window',params.inner_avg_start_stable_window, ...
    'min_price_updates',params.inner_avg_min_price_updates, ...
    'min_samples',params.inner_avg_min_samples, ...
    'formal_cv_stable_window',params.inner_formal_cv_stable_window);

det = cell(numel(call_counts),1);
fast = cell(numel(call_counts),1);
for q = 1:numel(call_counts)
    det{q} = callLocal(params,community_id,call_counts(q),false,true, ...
        max_test_iter,rng_config,avg_config);
    fast{q} = callLocal(params,community_id,call_counts(q),true,true, ...
        max_test_iter,rng_config,avg_config);
end
fast_audit_off = callLocal(params,community_id,2,true,false, ...
    max_test_iter,rng_config,avg_config);
fast_call2_repeat = callLocal(params,community_id,2,true,true, ...
    max_test_iter,rng_config,avg_config);

rows = numel(call_counts);
call_count_col = call_counts(:);
delay_seed = zeros(rows,1);
qre_seed = zeros(rows,1);
audit_seed = zeros(rows,1);
delay_hash = cell(rows,1);
update_hash = cell(rows,1);
qre_hash = cell(rows,1);
for q = 1:rows
    delay_seed(q) = fast{q}.inner_delay_seed;
    qre_seed(q) = fast{q}.qre_noise_seed;
    audit_seed(q) = fast{q}.qre_audit_seed;
    delay_hash{q} = fast{q}.delay_sequence_hash;
    update_hash{q} = fast{q}.update_sequence_hash;
    qre_hash{q} = fast{q}.qre_noise_sequence_hash;
end
seed_col = table(call_count_col,delay_seed,qre_seed,audit_seed,delay_hash, ...
    update_hash,qre_hash,'VariableNames',{'call_count','delay_seed', ...
    'qre_seed','audit_seed','delay_hash','update_hash','qre_hash'});

same_seed_replay = fast_call2_repeat.inner_delay_seed == fast{2}.inner_delay_seed && ...
    fast_call2_repeat.qre_noise_seed == fast{2}.qre_noise_seed && ...
    fast_call2_repeat.qre_audit_seed == fast{2}.qre_audit_seed;
same_hash_replay = strcmp(fast_call2_repeat.delay_sequence_hash,fast{2}.delay_sequence_hash) && ...
    strcmp(fast_call2_repeat.update_sequence_hash,fast{2}.update_sequence_hash) && ...
    strcmp(fast_call2_repeat.qre_noise_sequence_hash,fast{2}.qre_noise_sequence_hash);
same_schedule_det_fast = true;
for q = 1:rows
    same_schedule_det_fast = same_schedule_det_fast && ...
        strcmp(det{q}.delay_sequence_hash,fast{q}.delay_sequence_hash) && ...
        strcmp(det{q}.update_sequence_hash,fast{q}.update_sequence_hash);
end
same_qre_audit_toggle = strcmp(fast_audit_off.qre_noise_sequence_hash, ...
    fast{2}.qre_noise_sequence_hash) && ...
    strcmp(fast_audit_off.delay_sequence_hash,fast{2}.delay_sequence_hash) && ...
    strcmp(fast_audit_off.update_sequence_hash,fast{2}.update_sequence_hash);
distinct_seed = numel(unique(delay_seed)) == rows && ...
    numel(unique(qre_seed)) == rows && numel(unique(audit_seed)) == rows;
distinct_delay_preview = numel(unique(delay_hash)) == rows;
distinct_update_preview = numel(unique(update_hash)) == rows;
det_call_counts = cellfun(@(r) r.local_call_count,det);
fast_call_counts = cellfun(@(r) r.local_call_count,fast);
call_count_reproduced = isequal(det_call_counts(:),call_counts(:)) && ...
    isequal(fast_call_counts(:),call_counts(:)) && ...
    fast_audit_off.local_call_count == 2 && fast_call2_repeat.local_call_count == 2;

pass = same_seed_replay && same_hash_replay && same_schedule_det_fast && ...
    same_qre_audit_toggle && distinct_seed && distinct_delay_preview && ...
    distinct_update_preview && call_count_reproduced;
report = struct('seed_table',seed_col,'pass',pass, ...
    'same_seed_replay',same_seed_replay,'same_hash_replay',same_hash_replay, ...
    'same_schedule_det_fast',same_schedule_det_fast, ...
    'same_qre_audit_toggle',same_qre_audit_toggle, ...
    'distinct_seed',distinct_seed,'distinct_delay_preview',distinct_delay_preview, ...
    'distinct_update_preview',distinct_update_preview, ...
    'call_count_reproduced',call_count_reproduced, ...
    'seed_derivation_policy',fast{1}.seed_derivation_policy);
save('S3_repeated_local_call_rng_test.mat','report','seed_col');
writetable(seed_col,'S3_repeated_local_call_rng_test.csv');
disp(seed_col);
fprintf('S3 repeated local-call RNG audit: %s\n',ternary(pass,'PASS','FAIL'));

    function res = callLocal(p,community,call_count,qre_noise,audit_enabled, ...
            iter_cap,rng_cfg,avg_cfg)
        s = p.start_idx(community):p.end_idx(community);
        res = localMarket_S3(p.c(s),p.b(s),p.a(community),p.D(s), ...
            p.init_rho(community),p.pg_max(s),p.pg_min(s),p.init_pi(community), ...
            p.init_pes(s),p.init_pg(s),p.init_pb(s),p.init_ps(s), ...
            p.init_pesc(community),p.errTol_LESMs(community), ...
            p.inner_cv_tol_kW(community),p.init_pi_0(community),p.pi_max,p.pi_min, ...
            true,p.beta_qre(s),p.qre_epsilon,p.agg_epsilon_i(community), ...
            p.qre_z_cap,p.qre_backoff_factor,p.qre_max_backoffs,p.inner_momentum, ...
            iter_cap,p.h0_max,p.min_inner_iter,p.inner_avg_start_iter, ...
            p.inner_cv_stop_enabled,p.qre_certificate_enabled,p.agg_certificate_enabled, ...
            p.agg_cert_tol,p.stable_inner_window,audit_enabled,1, ...
            p.qre_audit_trace_community_full,p.qre_audit_seed, ...
            p.agg_gap_diagnostic_enabled,qre_noise,p.diagnostic_record_every, ...
            p.exact_sync_diagnostic_every,p.rolling_window,false,inf, ...
            1,community,rng_cfg,avg_cfg,call_count);
    end

    function value = ternary(condition,true_value,false_value)
        if condition, value = true_value; else, value = false_value; end
    end
end
