function output = run_S3_rng_stream_audit_test(max_iter_local)
%RUN_S3_RNG_STREAM_AUDIT_TEST Verify stream independence and repeatability.

if nargin < 1 || isempty(max_iter_local)
    max_iter_local = 1000;
end
params = load('params.mat');
community_id = 1;
idx = params.start_idx(community_id):params.end_idx(community_id);
rng_config = struct('inner_delay_seed',params.rng_seeds.inner_delay, ...
    'qre_noise_seed',params.rng_seeds.qre_noise,'qre_audit_seed',params.rng_seeds.qre_audit);
avg_config = struct('policy','dynamic_stable_start', ...
    'start_cv_factor',params.inner_avg_start_cv_factor, ...
    'start_price_factor',params.inner_avg_start_price_factor, ...
    'start_stable_window',params.inner_avg_start_stable_window, ...
    'min_price_updates',params.inner_avg_min_price_updates, ...
    'min_samples',params.inner_avg_min_samples);

fast_audit_on = run_once(true);
fast_audit_off = run_once(false);
fast_repeat = run_once(true);

output = struct();
output.same_audit_qre_trace = isequaln(fast_audit_on.trace_lambda,fast_audit_off.trace_lambda) && ...
    isequaln(fast_audit_on.trace_cv_held_kW,fast_audit_off.trace_cv_held_kW);
output.same_audit_delay_hash = strcmp(fast_audit_on.delay_sequence_hash,fast_audit_off.delay_sequence_hash);
output.same_audit_update_hash = strcmp(fast_audit_on.update_sequence_hash,fast_audit_off.update_sequence_hash);
output.same_repeat_qre_trace = isequaln(fast_audit_on.trace_lambda,fast_repeat.trace_lambda) && ...
    isequaln(fast_audit_on.trace_cv_held_kW,fast_repeat.trace_cv_held_kW);
output.same_repeat_delay_hash = strcmp(fast_audit_on.delay_sequence_hash,fast_repeat.delay_sequence_hash);
output.same_repeat_update_hash = strcmp(fast_audit_on.update_sequence_hash,fast_repeat.update_sequence_hash);
output.fast_audit_on = fast_audit_on;
output.fast_audit_off = fast_audit_off;
output.fast_repeat = fast_repeat;
output.max_inner_iter = max_iter_local;
output.community_id = community_id;
timestamp = datestr(now,'yyyymmdd_HHMMSS');
save(sprintf('S3_rng_stream_audit_test_community_%d_%s.mat',community_id,timestamp), ...
    'output','-v7');
fprintf('audit_on_vs_off: trace=%d delay=%d update=%d; repeat: trace=%d delay=%d update=%d\n', ...
    output.same_audit_qre_trace,output.same_audit_delay_hash, ...
    output.same_audit_update_hash,output.same_repeat_qre_trace, ...
    output.same_repeat_delay_hash,output.same_repeat_update_hash);

    function diagnostic = run_once(audit_enabled_local)
        diagnostic = localMarket_S3( ...
            params.c(idx),params.b(idx),params.a(community_id),params.D(idx),params.init_rho(community_id), ...
            params.pg_max(idx),params.pg_min(idx),params.init_pi(community_id),params.init_pes(idx), ...
            params.init_pg(idx),params.init_pb(idx),params.init_ps(idx),params.init_pesc(community_id), ...
            params.errTol_LESMs(community_id),params.inner_cv_tol_kW(community_id), ...
            params.init_pi_0(community_id),params.pi_max,params.pi_min,true,params.beta_qre(idx), ...
            params.qre_epsilon,params.agg_epsilon_i(community_id),params.qre_z_cap, ...
            params.qre_backoff_factor,params.qre_max_backoffs,params.inner_momentum, ...
            max_iter_local,params.h0_max,params.min_inner_iter,params.inner_avg_start_iter, ...
            params.inner_cv_stop_enabled,params.qre_certificate_enabled, ...
            params.agg_certificate_enabled,params.agg_cert_tol,params.stable_inner_window, ...
            audit_enabled_local,params.qre_audit_rate,params.qre_audit_trace_community_full, ...
            params.qre_audit_seed,params.agg_gap_diagnostic_enabled,true, ...
            params.diagnostic_record_every,params.exact_sync_diagnostic_every,params.rolling_window, ...
            false,inf,1,community_id,rng_config,avg_config);
    end
end
