function output_files = run_S3_inner_diagnostic()
%RUN_S3_INNER_DIAGNOSTIC Run the two single-community S3 inner diagnostics.
% This helper intentionally does not call upperMarketS3 or any S0-S2 code.

load('params.mat');

diagnostic_community_id = 1;
diagnostic_max_inner_iter = 50000;
diagnostic_record_every_local = 10;
exact_sync_every_local = 100;
rolling_window_local = 200;
diagnostic_record_trace = true;
diagnostic_safety = inner_step_safety;
idx = start_idx(diagnostic_community_id):end_idx(diagnostic_community_id);
timestamp = datestr(now,'yyyymmdd_HHMMSS');
mode_names = {'deterministic','fast_qre'};
output_files = cell(2,1);

for mode_idx = 1:2
    qre_noise_enabled_local = mode_idx == 2;
    rng(rng_seeds.outer_schedule,'twister');

    diagnostic = localMarket_S3( ...
        c(idx),b(idx),a(diagnostic_community_id),D(idx), ...
        init_rho(diagnostic_community_id),pg_max(idx),pg_min(idx), ...
        init_pi(diagnostic_community_id),init_pes(idx),init_pg(idx), ...
        init_pb(idx),init_ps(idx),init_pesc(diagnostic_community_id), ...
        errTol_LESMs(diagnostic_community_id),inner_cv_tol_kW(diagnostic_community_id), ...
        init_pi_0(diagnostic_community_id),pi_max,pi_min,diagnostic_record_trace, ...
        beta_qre(idx),qre_epsilon,agg_epsilon_i(diagnostic_community_id), ...
        qre_z_cap,qre_backoff_factor,qre_max_backoffs,inner_momentum, ...
        diagnostic_max_inner_iter,h0_max,min_inner_iter,inner_avg_start_iter, ...
        inner_cv_stop_enabled,qre_certificate_enabled,agg_certificate_enabled, ...
        agg_cert_tol,stable_inner_window,qre_audit_enabled,qre_audit_rate, ...
        qre_audit_trace_community_full,qre_audit_seed,agg_gap_diagnostic_enabled, ...
        qre_noise_enabled_local,diagnostic_record_every_local,exact_sync_every_local, ...
        rolling_window_local,false,inf,1,diagnostic_community_id);

    diagnostic_config = struct();
    diagnostic_config.mode = mode_names{mode_idx};
    diagnostic_config.community_id = diagnostic_community_id;
    diagnostic_config.inner_step_safety = diagnostic_safety;
    diagnostic_config.max_inner_iter = diagnostic_max_inner_iter;
    diagnostic_config.record_every = diagnostic_record_every_local;
    diagnostic_config.exact_sync_every = exact_sync_every_local;
    diagnostic_config.rolling_window = rolling_window_local;
    diagnostic_config.run_profile = run_profile;
    diagnostic_config.qre_noise_enabled = qre_noise_enabled_local;
    diagnostic_config.rng_seed = rng_seeds.outer_schedule;
    diagnostic_config.params_source = 'params.mat';

    filename = sprintf('S3_inner_diagnostic_%s_community_%d_safety_%s_max_%d_%s.mat', ...
        mode_names{mode_idx},diagnostic_community_id, ...
        strrep(sprintf('%.2f',diagnostic_safety),'.','p'), ...
        diagnostic_max_inner_iter,timestamp);
    save(filename,'diagnostic','diagnostic_config','-v7');
    output_files{mode_idx} = fullfile(pwd,filename);

    print_checkpoints(diagnostic,diagnostic_config);
end
end

function print_checkpoints(diagnostic,config)
checkpoint_h = [1,100,500,1000,2000,5000,10000,20000,50000];
fprintf('\n[%s] community=%d, safety=%.2f, max_inner_iter=%d\n', ...
    config.mode,config.community_id,config.inner_step_safety,config.max_inner_iter);
fprintf('h lambda lambda_error lambda_step held exact_sync avg rolling max_age mean_age\n');
for h_target = checkpoint_h
    trace_idx = find(diagnostic.trace_h == h_target,1,'last');
    if isempty(trace_idx)
        trace_idx = find(diagnostic.trace_h <= h_target,1,'last');
    end
    if isempty(trace_idx)
        fprintf('%d NaN NaN NaN NaN NaN NaN NaN NaN NaN\n',h_target);
    else
        fprintf('%d %.12g %.6g %.6g %.6g %.6g %.6g %.6g %.6g %.6g\n', ...
            h_target,diagnostic.trace_lambda(trace_idx), ...
            diagnostic.trace_lambda_error(trace_idx),diagnostic.trace_lambda_step(trace_idx), ...
            diagnostic.trace_cv_held_kW(trace_idx),diagnostic.trace_cv_exact_sync_kW(trace_idx), ...
            diagnostic.trace_cv_avg_kW(trace_idx),diagnostic.trace_cv_rolling_kW(trace_idx), ...
            diagnostic.trace_max_age(trace_idx),diagnostic.trace_mean_age(trace_idx));
    end
end
fprintf('final: success=%d iter=%d stop=%s lambda_exact=%.12g lambda_error=%.6g held=%.6g exact_sync=%.6g avg=%.6g rolling=%.6g max_age=%g mean_age=%.6g\n', ...
    diagnostic.success,diagnostic.iter,diagnostic.stop_reason,diagnostic.lambda_exact, ...
    diagnostic.final_lambda_error,diagnostic.cv_held_final_kW, ...
    diagnostic.cv_exact_sync_final_kW,diagnostic.cv_avg_final_kW, ...
    diagnostic.cv_rolling_final_kW,diagnostic.max_observed_EU_age, ...
    diagnostic.mean_observed_EU_age);
end
