function summary = run_S3_inner_fixed_probe()
%RUN_S3_INNER_FIXED_PROBE  Short deterministic probe of fixed-start averaging.
% This is a diagnostic override; it does not run upperMarketS3.

P = load('params.mat');
community_list = [1 49 71];
max_inner_iter_probe = 3000;
records = repmat(struct('community_id',NaN,'success',false,'iter',NaN, ...
    'price_updates',NaN,'inner_avg_cnt',NaN,'pesc_raw',NaN,'pes_sum',NaN, ...
    'inner_cv_kW',NaN,'lambda_final',NaN,'stop_reason',''),numel(community_list),1);

avg_config = struct('policy','fixed_start', ...
    'policy_version','A2_fixed_start_v1', ...
    'start_cv_factor',P.inner_avg_start_cv_factor, ...
    'start_price_factor',P.inner_avg_start_price_factor, ...
    'start_stable_window',P.inner_avg_start_stable_window, ...
    'min_price_updates',P.inner_avg_min_price_updates, ...
    'min_samples',P.inner_avg_min_samples, ...
    'formal_cv_stable_window',P.inner_formal_cv_stable_window);
rng_config = P.rng_seeds;

for ci = 1:numel(community_list)
    i = community_list(ci);
    idx = P.start_idx(i):P.end_idx(i);
    r = localMarket_S3(P.c(idx),P.b(idx),P.a(i),P.D(idx),P.init_rho(i), ...
        P.pg_max(idx),P.pg_min(idx),P.init_pi(i),P.init_pes(idx),P.init_pg(idx), ...
        P.init_pb(idx),P.init_ps(idx),P.init_pesc(i),P.errTol_LESMs(i), ...
        P.inner_cv_tol_kW(i),P.init_pi_0(i),P.pi_max,P.pi_min,false, ...
        P.beta_qre(idx),P.qre_epsilon,P.agg_epsilon_i(i),P.qre_z_cap, ...
        P.qre_backoff_factor,P.qre_max_backoffs,P.inner_momentum,max_inner_iter_probe, ...
        P.h0_max,P.min_inner_iter,P.inner_avg_start_iter,true,false,false,P.agg_cert_tol, ...
        P.stable_inner_window,false,0,false,P.qre_audit_seed,false,false, ...
        P.diagnostic_record_every,P.exact_sync_diagnostic_every,P.rolling_window, ...
        false,inf,1,i,rng_config,avg_config,1);
    records(ci).community_id = i;
    records(ci).success = logical(r.success);
    records(ci).iter = r.iter;
    records(ci).price_updates = r.price_updates;
    records(ci).inner_avg_cnt = r.inner_avg_cnt;
    records(ci).pesc_raw = r.pesc_agg_raw;
    records(ci).pes_sum = r.pes_sum;
    records(ci).inner_cv_kW = r.inner_cv_kW;
    records(ci).lambda_final = r.pi;
    records(ci).stop_reason = r.stop_reason;
end

summary = struct();
summary.community_list = community_list;
summary.records = records;
summary.formal_parameters = struct('inner_avg_policy',P.inner_avg_policy, ...
    'inner_avg_policy_version',P.inner_avg_policy_version, ...
    'inner_avg_start_iter',P.inner_avg_start_iter, ...
    'inner_cv_stop_enabled',P.inner_cv_stop_enabled);
summary.test_overrides = struct('qre_noise_enabled',false, ...
    'qre_audit_enabled',false,'max_inner_iter',max_inner_iter_probe, ...
    'label','short deterministic diagnostic only; not formal S3');
summary.no_nan_inf = all(isfinite([records.pesc_raw])) && ...
    all(isfinite([records.pes_sum])) && all(isfinite([records.inner_cv_kW]));
summary.fixed_start_observed = all([records.inner_avg_cnt] >= 0);
summary.success_gate = summary.no_nan_inf && summary.fixed_start_observed;
save('S3_inner_fixed_probe.mat','summary');
fprintf('S3 fixed-start inner probe: %s\n',ternary(summary.success_gate,'PASS','FAIL'));
for ci = 1:numel(records)
    fprintf('community=%d success=%d iter=%d avg=%d raw=%.6f sum=%.6f CV=%.6f stop=%s\n', ...
        records(ci).community_id,records(ci).success,records(ci).iter, ...
        records(ci).inner_avg_cnt,records(ci).pesc_raw,records(ci).pes_sum, ...
        records(ci).inner_cv_kW,records(ci).stop_reason);
end

    function out = ternary(condition,yes_value,no_value)
        if condition, out = yes_value; else, out = no_value; end
    end
end
