function result = run_S2_A2_full_single_community_test(community_id,qre_mode)
%RUN_S2_A2_FULL_SINGLE_COMMUNITY_TEST Complete S2 local A2 validation.

root = fileparts(mfilename('fullpath'));
cd(root);
p = load('params.mat');
if nargin < 1 || isempty(community_id), community_id = 1; end
if nargin < 2 || isempty(qre_mode), qre_mode = 'deterministic'; end
validateattributes(community_id,{'numeric'},{'scalar','integer','>=',1,'<=',p.num_LESMs});
qre_mode = char(qre_mode);
if ~ismember(qre_mode,{'deterministic','fast_qre'})
    error('qre_mode must be deterministic or fast_qre.');
end

s = p.start_idx(community_id):p.end_idx(community_id);
rng_config = struct('inner_delay_seed',p.rng_seeds.inner_delay, ...
    'qre_noise_seed',p.rng_seeds.qre_noise, ...
    'qre_audit_seed',p.rng_seeds.qre_audit, ...
    'qre_noise_enabled',strcmp(qre_mode,'fast_qre'), ...
    'qre_audit_enabled',true,'qre_audit_rate',0.01);
avg_config = struct('policy','A2_dynamic_stable_start', ...
    'policy_version','A2_dynamic_stable_start_v1', ...
    'start_cv_factor',p.inner_avg_start_cv_factor, ...
    'start_price_factor',p.inner_avg_start_price_factor, ...
    'start_stable_window',p.inner_avg_start_stable_window, ...
    'min_price_updates',p.inner_avg_min_price_updates, ...
    'min_samples',p.inner_avg_min_samples, ...
    'formal_cv_stable_window',p.inner_formal_cv_stable_window, ...
    'price_stable_window',p.stable_inner_window);

t0 = tic;
r = localMarket_S2(p.c(s),p.b(s),p.a(community_id),p.D(s), ...
    p.init_rho(community_id),p.pg_max(s),p.pg_min(s),p.init_pi(community_id), ...
    p.init_pes(s),p.init_pg(s),p.init_pb(s),p.init_ps(s), ...
    p.init_pesc(community_id),p.errTol_LESMs(community_id), ...
    p.inner_cv_tol_kW(community_id),p.init_pi_0(community_id),p.pi_max,p.pi_min, ...
    false,p.beta_qre(s),p.qre_epsilon,p.agg_epsilon_i(community_id), ...
    p.qre_z_cap,p.qre_backoff_factor,p.inner_momentum,p.max_inner_iter, ...
    p.h0_max,p.min_inner_iter,p.inner_avg_start_iter,p.inner_cv_stop_enabled, ...
    p.qre_certificate_enabled,p.agg_certificate_enabled,false,inf, ...
    1,community_id,rng_config,avg_config,1);
runtime_s = toc(t0);

formal_cv_pass = isfinite(r.inner_cv_kW) && ...
    r.inner_cv_kW <= p.inner_cv_tol_kW(community_id);
success_gate = logical(r.success) && formal_cv_pass && ...
    r.price_updates <= p.max_inner_iter && ...
    r.wall_iter <= r.max_inner_wall_iter && ...
    logical(r.qre_all_certificate_pass) && isfinite(r.inner_cv_kW);
summary = table(community_id,{qre_mode},r.wall_iter,r.price_updates, ...
    r.inner_avg_start_price_update,r.inner_avg_cnt,r.inner_cv_kW, ...
    p.inner_cv_tol_kW(community_id),r.held_cv_kW,{r.stop_reason},runtime_s, ...
    r.qre_gap_max,r.qre_gap_p95,r.qre_audit_count,success_gate, ...
    'VariableNames',{'community_id','mode','wall_event','price_updates', ...
    'avg_start_price_update','avg_samples','formal_cv_kW','cv_tol_kW', ...
    'held_cv_kW','stop_reason','runtime_s','qre_gap_max','qre_gap_p95', ...
    'qre_audit_count','success_gate'});
result = struct('summary',summary,'res',r,'success_gate',success_gate, ...
    'community_id',community_id,'qre_mode',qre_mode, ...
    'max_inner_price_updates',r.max_inner_price_updates, ...
    'max_inner_wall_iter',r.max_inner_wall_iter, ...
    'seed_derivation_policy',r.seed_derivation_policy);
file_tag = sprintf('S2_A2_full_community_%03d_%s',community_id,qre_mode);
save([file_tag,'.mat'],'result','summary');
writetable(summary,[file_tag,'.csv']);
disp(summary);
fprintf('S2 full local A2 community %d (%s): %s\n', ...
    community_id,qre_mode,ternary(success_gate,'PASS','FAIL'));

    function value = ternary(condition,true_value,false_value)
        if condition, value = true_value; else, value = false_value; end
    end
end
